version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    command: "elasticsearch -E http.compression=true -E discovery.type=single-node -E bootstrap.memory_lock=true -E cluster.name=clusterA"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9310:9300"
      - "9210:9200"
    networks:
      defaultEnvironment:
        ipv4_address: 172.16.239.10
networks:
  defaultEnvironment:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.239.11/30
#        gateway: 172.16.239.9 # in version 3 of docker-compose, the keyword gateway is not supported https://docs.docker.com/compose/compose-file/#ipam